services:
  db:
    container_name: sportsbook-db
    image: postgres:16
    environment:
      POSTGRES_DB: sportsbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sportsbook-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sportsbook-network:
    driver: bridge

volumes:
  postgres_data: